#ifndef THREE_ADDR_CODE_H
#define THREE_ADDR_CODE_H

#include "ast.h"
#include <fstream>
#include <string>
#include <map>

using namespace std;

class ThreeAddrCodeGenerator {
private:
    ProgramNode* ast_root;
    ofstream& outcode;
    map<string, string> symbol_to_temp;
    int temp_count;
    int label_count;

public:
    ThreeAddrCodeGenerator(ProgramNode* root, ofstream& out)
        : ast_root(root), outcode(out), temp_count(0), label_count(0) {}

    void generate() {
        // Header
        outcode << "//========== THREE ADDRESS CODE ==========" << "\n";
        outcode << "\n";
        outcode << "// This code was generated by a two-pass compiler" << "\n";
        outcode << "// Format: " << "\n";
        outcode << "// - t0, t1, etc. are temporary variables" << "\n";
        outcode << "// - L0, L1, etc. are labels for jumps" << "\n";
        outcode << "// - Operations follow the three-address code format" << "\n";
        outcode << "\n";
        outcode << "// Three Address Code" << "\n";
        outcode << "\n";

        // Generate code from AST
        ast_root->generate_code(outcode, symbol_to_temp, temp_count, label_count);

        // Footer
        outcode << "\n";
        outcode << "//========== END OF CODE ==========" << "\n";
    }
};

#endif // THREE_ADDR_CODE_H
